# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "PodSample" do
    pod '', :git => 'https://github.com/chris-garrett/cocoapod-framework.git', :branch => 'new-framework'
end

target "PodSampleTests" do

end

